### ISSUE TITLE
Certificate expired for get.infini.cloud

### ISSUE THREAD

**Issue by mikesmitharoo** [infinilabs/analysis-stconvert#53]
### Description

The certificate for the get.infini.cloud domain expired on Sunday. This is what you now see when trying to go to the site. 

e.g. https://get.infini.cloud/opensearch/analysis-stconvert/

<img width="1354" alt="image" src="https://github.com/user-attachments/assets/47e7f4cf-47ef-41ba-b451-ff4ba6525dd1">

It also means refresh downloads of the plugin to install against an OpenSearch cluster fail with the following:

```
 => ERROR [opensearch-primary 3/3] RUN bin/opensearch-plugin install https://get.infini.cloud/opensearch/analysis-stconvert/2.15.0                                                                                                                                                                              2.8s
------
 > [opensearch-primary 3/3] RUN bin/opensearch-plugin install https://get.infini.cloud/opensearch/analysis-stconvert/2.15.0:
1.524 -> Installing https://get.infini.cloud/opensearch/analysis-stconvert/2.15.0
1.525 -> Downloading https://get.infini.cloud/opensearch/analysis-stconvert/2.15.0
2.788 -> Failed installing https://get.infini.cloud/opensearch/analysis-stconvert/2.15.0
2.788 -> Rolling back https://get.infini.cloud/opensearch/analysis-stconvert/2.15.0
2.788 -> Rolled back https://get.infini.cloud/opensearch/analysis-stconvert/2.15.0
2.789 Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
2.790   at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130)
2.790   at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
2.790   at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
2.790   at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
2.790   at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1318)
2.790   at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1195)
2.791   at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1138)
2.791   at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:393)
2.791   at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:476)
2.792   at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:447)
2.792   at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
2.792   at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
2.792   at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
2.792   at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
2.792   at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
2.792   at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
2.792   at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:586)
2.792   at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
2.793   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
2.793   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
2.793   at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
2.793   at org.opensearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:456)
2.793   at org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:341)
2.794   at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:273)
2.794   at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:250)
2.794   at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
2.794   at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
2.794   at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
2.794   at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
2.795   at org.opensearch.cli.Command.main(Command.java:101)
2.795   at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
2.795 Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
2.795   at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:318)
2.795   at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:267)
2.795   at java.base/sun.security.validator.Validator.validate(Validator.java:256)
2.795   at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:230)
2.795   at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
2.795   at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1302)
2.795   ... 26 more
2.796 Caused by: java.security.cert.CertPathValidatorException: validity check failed
2.796   at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
2.796   at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
2.796   at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
2.796   at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
2.797   at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
2.797   at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:313)
2.797   ... 31 more
2.798 Caused by: java.security.cert.CertificateExpiredException: NotAfter: Sat Oct 12 23:59:59 UTC 2024
2.799   at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:182)
2.799   at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:534)
2.799   at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
2.799   at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
2.799   at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
2.799   ... 36 more
------
failed to solve: process "/bin/sh -c bin/opensearch-plugin install https://get.infini.cloud/opensearch/analysis-stconvert/2.15.0" did not complete successfully: exit code: 1

```

### Steps to reproduce

1. Delete any caches of existing plugin (or try a new verison)
2. Try to install the plugin against applicable OpenSearch cluster 
3. See error

### Expected behavior

Able to install the plugin against OpenSearch cluster without bypassing security

### Actual behavior

Unable to install plugin against OpenSearch cluster due to security checks failing due to an expired certificate.

### Environment

- Versions: OpenSearch 2.13
- Operating system and version: macOS

**Comment by medcl** [comment]
Thanks for reporting this, already fixed :)
